-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DYK_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DYK_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DYK_db` DEFAULT CHARACTER SET utf8 ;
USE `DYK_db` ;

-- -----------------------------------------------------
-- Table `DYK_db`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`USUARIO` (
  `COD_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` VARCHAR(50) NOT NULL,
  `SOBRENOME_USUARIO` VARCHAR(50) NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `APELIDO_USUARIO` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `IND_ATIVO` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`COD_USUARIO`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DYK_db`.`PERSONAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`PERSONAGEM` (
  `COD_PERSONAGEM` INT NOT NULL AUTO_INCREMENT,
  `NOME_PERSONAGEM` VARCHAR(50) NOT NULL,
  `TEMPO_VIDA` FLOAT NOT NULL DEFAULT 100.0,
  `IND_ESCOLHIDO` TINYINT NOT NULL DEFAULT 0,
  `USUARIO_COD_USUARIO` INT NOT NULL,
  PRIMARY KEY (`COD_PERSONAGEM`),
  UNIQUE INDEX `COD_PERSONAGEM_UNIQUE` (`COD_PERSONAGEM` ASC) VISIBLE,
  INDEX `fk_PERSONAGEM_USUARIO1_idx` (`USUARIO_COD_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONAGEM_USUARIO1`
    FOREIGN KEY (`USUARIO_COD_USUARIO`)
    REFERENCES `DYK_db`.`USUARIO` (`COD_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DYK_db`.`HABILIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`HABILIDADE` (
  `COD_HABILIDADE` INT NOT NULL AUTO_INCREMENT,
  `DESC_HABILIDADE` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`COD_HABILIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DYK_db`.`HABILIDADE_PERSONAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`HABILIDADE_PERSONAGEM` (
  `COD_HABILIDADE` INT NOT NULL,
  `COD_PERSONAGEM` INT NOT NULL,
  `DATA_CRIACAO` TIMESTAMP NULL,
  PRIMARY KEY (`COD_HABILIDADE`, `COD_PERSONAGEM`),
  INDEX `fk_HABILIDADE_has_PERSONAGEM_PERSONAGEM1_idx` (`COD_PERSONAGEM` ASC) VISIBLE,
  INDEX `fk_HABILIDADE_has_PERSONAGEM_HABILIDADE1_idx` (`COD_HABILIDADE` ASC) VISIBLE,
  CONSTRAINT `fk_HABILIDADE_has_PERSONAGEM_HABILIDADE1`
    FOREIGN KEY (`COD_HABILIDADE`)
    REFERENCES `DYK_db`.`HABILIDADE` (`COD_HABILIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HABILIDADE_has_PERSONAGEM_PERSONAGEM1`
    FOREIGN KEY (`COD_PERSONAGEM`)
    REFERENCES `DYK_db`.`PERSONAGEM` (`COD_PERSONAGEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DYK_db`.`TIPO_PERGUNTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`TIPO_PERGUNTA` (
  `COD_TIPO_PERGUNTA` INT NOT NULL AUTO_INCREMENT,
  `DESC_TIPO_PERGUNTA` VARCHAR(50) NULL,
  PRIMARY KEY (`COD_TIPO_PERGUNTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DYK_db`.`PERGUNTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`PERGUNTA` (
  `COD_PERGUNTA` INT NOT NULL AUTO_INCREMENT,
  `PERGUNTA` VARCHAR(100) NOT NULL,
  `COD_TIPO_PERGUNTA` INT NOT NULL,
  PRIMARY KEY (`COD_PERGUNTA`, `COD_TIPO_PERGUNTA`),
  INDEX `fk_PERGUNTA_TIPO_PERGUNTA1_idx` (`COD_TIPO_PERGUNTA` ASC) VISIBLE,
  CONSTRAINT `fk_PERGUNTA_TIPO_PERGUNTA1`
    FOREIGN KEY (`COD_TIPO_PERGUNTA`)
    REFERENCES `DYK_db`.`TIPO_PERGUNTA` (`COD_TIPO_PERGUNTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DYK_db`.`RESPOSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`RESPOSTA` (
  `COD_RESPOSTA` INT NOT NULL AUTO_INCREMENT,
  `RESPOSTA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`COD_RESPOSTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DYK_db`.`PERGUNTA_RESPOSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DYK_db`.`PERGUNTA_RESPOSTA` (
  `COD_PERGUNTA` INT NOT NULL,
  `COD_TIPO_PERGUNTA` INT NOT NULL,
  `COD_RESPOSTA` INT NOT NULL,
  `IND_RESPOSTA_CORRETA` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`COD_PERGUNTA`, `COD_TIPO_PERGUNTA`, `COD_RESPOSTA`),
  INDEX `fk_PERGUNTA_has_RESPOSTA_RESPOSTA1_idx` (`COD_RESPOSTA` ASC) VISIBLE,
  INDEX `fk_PERGUNTA_has_RESPOSTA_PERGUNTA1_idx` (`COD_PERGUNTA` ASC, `COD_TIPO_PERGUNTA` ASC) VISIBLE,
  CONSTRAINT `fk_PERGUNTA_has_RESPOSTA_PERGUNTA1`
    FOREIGN KEY (`COD_PERGUNTA` , `COD_TIPO_PERGUNTA`)
    REFERENCES `DYK_db`.`PERGUNTA` (`COD_PERGUNTA` , `COD_TIPO_PERGUNTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERGUNTA_has_RESPOSTA_RESPOSTA1`
    FOREIGN KEY (`COD_RESPOSTA`)
    REFERENCES `DYK_db`.`RESPOSTA` (`COD_RESPOSTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
